### ISSUE TITLE
No Kawi repha in Noto Sans Balinese

### ISSUE THREAD

**Issue by dscorbett** [notofonts/balinese#2]
### Font
NotoSansBalinese-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansBalinese-unhinted.zip
Date: 2018-04-02

### Font version
Version 1.03 uh

### Issue
Noto Sans Balinese does not support the Kawi repha [as described in _The Unicode Standard_](https://www.unicode.org/versions/Unicode10.0.0/ch17.pdf#page=10). This is presumably because OpenType has no language system tag for Kawi.

### Character data
ᬭ᭄ᬫ
U+1B2D BALINESE LETTER RA
U+1B44 BALINESE ADEG ADEG
U+1B2B BALINESE LETTER MA

**Comment by simoncozens** [comment]
If Kawi Repha is gone, is there still an issue here?

**Comment by dscorbett** [comment]
Yes, but now it is the opposite issue. The font was changed to support the Kawi repha as formerly described in <i>The Unicode Standard</i>, but now that Unicode no longer recommends that, it needs reverting.

**Comment by verdy-p** [comment]
The newly encoded Kawi script (since Unicode 15.0 released on September 2022) is separate from Balinese, due to its complex composition and layout.

So this bug may be closed or renamed for "no font for Kawi" and tracked (with a separate bug also created for "no font for Nag Mundari").

An additional tracking bug should be created for needed updates for Unicode 15.0 (Kawi, Nag Mundari, additional sets of digits in other scripts, some letters added in various scripts, addition of new emojis, new symbols, and a new CJK ideographs...). This adds 7 new blocks in the UCD (including the 2 blocks for the 2 newly encoded scripts). The summary of additions and changes is on https://unicode.org/versions/Unicode15.0.0/

**Comment by simoncozens** [comment]
We don't need tracking issues for Noto gaps; we track these at the [Noto overview page](https://notofonts.github.io/overview/). (There is another Python script which produces the gap list as a textual summary, but I haven't checked that in yet.) Kawi will be one of the scripts we are commissioning in 2023. It's in hand. :-)

So what we need to do here is remove the premature support for the kawi repha that was added.
